version: "3"

services:
  # app-warehouse:
  #   build:
  #     context: .
  #     dockerfile: ./docker/app-warehouse.Dockerfile
  #   image: app-warehouse:latest
  #   restart: always
  #   container_name: app-warehouse
  #   volumes:
  #     - ./app-warehouse:/app-warehouse/
  #     - app-volume:/app-warehouse/node_modules
  #   ports:
  #     - "3400:3000"
  #   networks:
  #     - app-backend

  db-warehouse:
    container_name: db-warehouse
    image: mysql:5.7
    restart: always
    ports:
      - "3308:3306"
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    networks:
      - app-backend
  
  db-admin:
    container_name: db-admin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db-warehouse
    networks:
      - app-backend

networks:
  app-backend:
volumes:
  app-volume:
  db-volume: